Add failed test to reproduce bug raising NoMethodError
Failures:

  1) Mrkt::Authentication#authenticate on a unexpected non json response should raise an Error
     Failure/Error: expect { subject }.to raise_error(Mrkt::Errors::Error)

       expected Mrkt::Errors::Unknown, got #<NoMethodError: undefined method `fetch' for "something wrong":String> with backtrace:
         # ./lib/mrkt/concerns/authentication.rb:34:in `block in authenticate'
         # ./lib/mrkt/concerns/authentication.rb:31:in `tap'
         # ./lib/mrkt/concerns/authentication.rb:31:in `authenticate'
         # ./spec/concerns/authentication_spec.rb:5:in `block (3 levels) in <top (required)>'
         # ./spec/concerns/authentication_spec.rb:22:in `block (5 levels) in <top (required)>'
         # ./spec/concerns/authentication_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/concerns/authentication_spec.rb:22:in `block (4 levels) in <top (required)>'